package musiclibrary;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Eskandar Atrakchi
 */
public class MusicLibraryGUI extends javax.swing.JFrame {

    /**
     * Creates new form MusicLibraryGUI
     */
    public MusicLibraryGUI() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Timer timer;
        timer = new Timer(1000, (ActionEvent e) -> {
            time();
        });
        timer.start();

        date();
    }
    
    public final void date() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        date.setText(year + "/" + (month + 1) + "/" + day);

    }

    public void time() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        time.setText(hour + ":" + minute + ":" + second);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        print_hiphopBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        print_likedBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        print_pianoBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        moveBTN = new javax.swing.JButton();
        repeatTOGGLE = new javax.swing.JToggleButton();
        backgroundLBL = new javax.swing.JLabel();
        colorblindLBL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();
        colorBlindMode = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        print_hiphopBTN.setBackground(new java.awt.Color(204, 204, 204));
        print_hiphopBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print_hiphopBTN.setForeground(new java.awt.Color(51, 51, 51));
        print_hiphopBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        print_hiphopBTN.setText("Print HipHop");
        jPanel1.add(print_hiphopBTN);
        print_hiphopBTN.setBounds(580, 660, 160, 50);

        addBTN.setBackground(new java.awt.Color(204, 204, 204));
        addBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBTN.setForeground(new java.awt.Color(51, 51, 51));
        addBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Allowance.png"))); // NOI18N
        addBTN.setText("Add");
        jPanel1.add(addBTN);
        addBTN.setBounds(1030, 660, 120, 50);

        print_likedBTN.setBackground(new java.awt.Color(204, 204, 204));
        print_likedBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print_likedBTN.setForeground(new java.awt.Color(51, 51, 51));
        print_likedBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        print_likedBTN.setText("Print Liked");
        jPanel1.add(print_likedBTN);
        print_likedBTN.setBounds(750, 660, 150, 50);

        deleteBTN.setBackground(new java.awt.Color(204, 204, 204));
        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(51, 51, 51));
        deleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_16x16.gif"))); // NOI18N
        deleteBTN.setText("Delete");
        jPanel1.add(deleteBTN);
        deleteBTN.setBounds(910, 660, 100, 50);

        print_pianoBTN.setBackground(new java.awt.Color(204, 204, 204));
        print_pianoBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print_pianoBTN.setForeground(new java.awt.Color(51, 51, 51));
        print_pianoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        print_pianoBTN.setText("Print Piano");
        jPanel1.add(print_pianoBTN);
        print_pianoBTN.setBounds(440, 660, 130, 50);

        exitBTN.setBackground(new java.awt.Color(204, 204, 204));
        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(51, 51, 51));
        exitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        jPanel1.add(exitBTN);
        exitBTN.setBounds(0, 10, 100, 50);

        moveBTN.setBackground(new java.awt.Color(204, 204, 204));
        moveBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        moveBTN.setForeground(new java.awt.Color(51, 51, 51));
        moveBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attach.png"))); // NOI18N
        moveBTN.setText("Move");
        jPanel1.add(moveBTN);
        moveBTN.setBounds(1050, 10, 100, 50);

        repeatTOGGLE.setBackground(new java.awt.Color(204, 204, 204));
        repeatTOGGLE.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        repeatTOGGLE.setForeground(new java.awt.Color(51, 51, 51));
        repeatTOGGLE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update icon.png"))); // NOI18N
        repeatTOGGLE.setText("Repeat");
        jPanel1.add(repeatTOGGLE);
        repeatTOGGLE.setBounds(300, 660, 120, 50);

        backgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pngtree-note-music-logo-watercolor-background-picture-image_1589075.png"))); // NOI18N
        jPanel1.add(backgroundLBL);
        backgroundLBL.setBounds(0, 0, 1520, 870);

        colorblindLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pexels-daniel-reche-3721941.jpg"))); // NOI18N
        jPanel1.add(colorblindLBL);
        colorblindLBL.setBounds(0, 10, 1270, 790);

        jMenuBar1.setToolTipText("Menu to view data ");

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        colorBlindMode.setText("Color-Blind?");
        colorBlindMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBlindModeMouseClicked(evt);
            }
        });
        jMenuBar1.add(colorBlindMode);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 723, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        JOptionPane.showMessageDialog(null , "Bye-Bye");
        System.exit(0);
        
    }                                       

    private boolean isLightMode = false;
    
    private void colorBlindModeMouseClicked(java.awt.event.MouseEvent evt) {                                            
        
        backgroundLBL.setVisible(isLightMode);
        
        colorblindLBL.setVisible(!isLightMode);
        
        isLightMode = !isLightMode;
        
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicLibraryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel backgroundLBL;
    private javax.swing.JMenu colorBlindMode;
    private javax.swing.JLabel colorblindLBL;
    private javax.swing.JMenu date;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton moveBTN;
    private javax.swing.JButton print_hiphopBTN;
    private javax.swing.JButton print_likedBTN;
    private javax.swing.JButton print_pianoBTN;
    private javax.swing.JToggleButton repeatTOGGLE;
    private javax.swing.JMenu time;
    // End of variables declaration                   
}
