package musiclibrary;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Eskandar Atrakchi
 */
public class MusicLibraryGUI extends javax.swing.JFrame {

    
    LikedSongsInterface likedSongs = new LikedSongsImpl();
    GenrePlaylistInterface genrePlaylist = new GenrePlaylistImpl();
        
    /**
     * Creates new form MusicLibraryGUI
     */
    public MusicLibraryGUI() {
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size = toolkit.getScreenSize();
        setLocation(size.width / 2 - getWidth() / 2, size.height / 2 - getHeight() / 2);

        Timer timer;
        timer = new Timer(1000, (ActionEvent e) -> {
            time();
        });
        timer.start();

        date();
    }
    
    public final void date() {

        Calendar cal = new GregorianCalendar();
        int month = cal.get(Calendar.MONTH);
        int year = cal.get(Calendar.YEAR);
        int day = cal.get(Calendar.DAY_OF_MONTH);

        date.setText(year + "/" + (month + 1) + "/" + day);

    }

    public void time() {

        Calendar cal = new GregorianCalendar();
        int second = cal.get(Calendar.SECOND);
        int minute = cal.get(Calendar.MINUTE);
        int hour = cal.get(Calendar.HOUR);

        time.setText(hour + ":" + minute + ":" + second);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        print_hiphopBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        print_likedBTN = new javax.swing.JButton();
        deleteBTN = new javax.swing.JButton();
        print_pianoBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        moveBTN = new javax.swing.JButton();
        titleTF = new javax.swing.JTextField();
        searchBTN = new javax.swing.JButton();
        sizeBTN = new javax.swing.JButton();
        artistLBL = new javax.swing.JLabel();
        titleLBL = new javax.swing.JLabel();
        repeatTOGGLE2 = new javax.swing.JToggleButton();
        artistTF = new javax.swing.JTextField();
        backgroundLBL = new javax.swing.JLabel();
        colorblindLBL = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        date = new javax.swing.JMenu();
        time = new javax.swing.JMenu();
        colorBlindMode = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        print_hiphopBTN.setBackground(new java.awt.Color(204, 204, 204));
        print_hiphopBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print_hiphopBTN.setForeground(new java.awt.Color(51, 51, 51));
        print_hiphopBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        print_hiphopBTN.setText("Print HipHop");
        jPanel1.add(print_hiphopBTN);
        print_hiphopBTN.setBounds(580, 660, 160, 50);

        addBTN.setBackground(new java.awt.Color(204, 204, 204));
        addBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addBTN.setForeground(new java.awt.Color(51, 51, 51));
        addBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Allowance.png"))); // NOI18N
        addBTN.setText("Add");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        jPanel1.add(addBTN);
        addBTN.setBounds(1030, 660, 120, 50);

        print_likedBTN.setBackground(new java.awt.Color(204, 204, 204));
        print_likedBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print_likedBTN.setForeground(new java.awt.Color(51, 51, 51));
        print_likedBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        print_likedBTN.setText("Print Liked");
        print_likedBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                print_likedBTNActionPerformed(evt);
            }
        });
        jPanel1.add(print_likedBTN);
        print_likedBTN.setBounds(750, 660, 150, 50);

        deleteBTN.setBackground(new java.awt.Color(204, 204, 204));
        deleteBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        deleteBTN.setForeground(new java.awt.Color(51, 51, 51));
        deleteBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete_16x16.gif"))); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBTN);
        deleteBTN.setBounds(910, 660, 100, 50);

        print_pianoBTN.setBackground(new java.awt.Color(204, 204, 204));
        print_pianoBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        print_pianoBTN.setForeground(new java.awt.Color(51, 51, 51));
        print_pianoBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/folder.png"))); // NOI18N
        print_pianoBTN.setText("Print Piano");
        jPanel1.add(print_pianoBTN);
        print_pianoBTN.setBounds(440, 660, 130, 50);

        exitBTN.setBackground(new java.awt.Color(204, 204, 204));
        exitBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        exitBTN.setForeground(new java.awt.Color(51, 51, 51));
        exitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/exit.png"))); // NOI18N
        exitBTN.setText("Exit");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        jPanel1.add(exitBTN);
        exitBTN.setBounds(0, 10, 100, 50);

        moveBTN.setBackground(new java.awt.Color(204, 204, 204));
        moveBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        moveBTN.setForeground(new java.awt.Color(51, 51, 51));
        moveBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attach.png"))); // NOI18N
        moveBTN.setText("Move");
        moveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBTNActionPerformed(evt);
            }
        });
        jPanel1.add(moveBTN);
        moveBTN.setBounds(1050, 10, 100, 50);
        jPanel1.add(titleTF);
        titleTF.setBounds(900, 480, 250, 40);

        searchBTN.setBackground(new java.awt.Color(204, 204, 204));
        searchBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        searchBTN.setForeground(new java.awt.Color(51, 51, 51));
        searchBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search.png"))); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        jPanel1.add(searchBTN);
        searchBTN.setBounds(160, 660, 130, 50);

        sizeBTN.setBackground(new java.awt.Color(204, 204, 204));
        sizeBTN.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sizeBTN.setForeground(new java.awt.Color(51, 51, 51));
        sizeBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/attachment-512.png"))); // NOI18N
        sizeBTN.setText("Size");
        sizeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sizeBTNActionPerformed(evt);
            }
        });
        jPanel1.add(sizeBTN);
        sizeBTN.setBounds(300, 660, 130, 50);

        artistLBL.setBackground(new java.awt.Color(0, 0, 0));
        artistLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        artistLBL.setForeground(new java.awt.Color(153, 153, 153));
        artistLBL.setText("Artist");
        jPanel1.add(artistLBL);
        artistLBL.setBounds(830, 550, 60, 40);

        titleLBL.setBackground(new java.awt.Color(0, 0, 0));
        titleLBL.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(153, 153, 153));
        titleLBL.setText("Title");
        jPanel1.add(titleLBL);
        titleLBL.setBounds(830, 480, 60, 40);

        repeatTOGGLE2.setBackground(new java.awt.Color(204, 204, 204));
        repeatTOGGLE2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        repeatTOGGLE2.setForeground(new java.awt.Color(51, 51, 51));
        repeatTOGGLE2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/update icon.png"))); // NOI18N
        repeatTOGGLE2.setText("Repeat");
        repeatTOGGLE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatTOGGLE2ActionPerformed(evt);
            }
        });
        jPanel1.add(repeatTOGGLE2);
        repeatTOGGLE2.setBounds(0, 500, 120, 50);
        repeatTOGGLE2.setEnabled(false);
        jPanel1.add(artistTF);
        artistTF.setBounds(900, 550, 250, 40);

        backgroundLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pngtree-note-music-logo-watercolor-background-picture-image_1589075.png"))); // NOI18N
        jPanel1.add(backgroundLBL);
        backgroundLBL.setBounds(0, 0, 1200, 870);

        colorblindLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/pexels-daniel-reche-3721941.jpg"))); // NOI18N
        jPanel1.add(colorblindLBL);
        colorblindLBL.setBounds(0, 10, 1200, 810);

        jTabbedPane1.addTab("LIKED SONGS", jPanel1);

        jMenuBar1.setToolTipText("Menu to view data ");

        date.setText("DATE");
        jMenuBar1.add(date);

        time.setText("TIME");
        jMenuBar1.add(time);

        colorBlindMode.setText("Color-Blind?");
        colorBlindMode.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colorBlindModeMouseClicked(evt);
            }
        });
        jMenuBar1.add(colorBlindMode);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 832, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        JOptionPane.showMessageDialog(null , "Bye-Bye");
        System.exit(0);
        
    }                                       

    private boolean isLightMode = false;
    
    private void colorBlindModeMouseClicked(java.awt.event.MouseEvent evt) {                                            
        
        backgroundLBL.setVisible(isLightMode);
        
        colorblindLBL.setVisible(!isLightMode);
        
        isLightMode = !isLightMode;
        
    }                                           

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {                                       
        
        if (artistTF.getText().isEmpty() == true || titleTF.getText().isEmpty() == true) {
            JOptionPane.showMessageDialog(null , "Please enter the title and the artist.");
        } else {
            likedSongs.addSong();
        }

    }                                      

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        if ( titleTF.getText().isEmpty() == true && artistTF.getText().isEmpty() == true ) {
            
            JOptionPane.showMessageDialog(null , "Please enter title or artist.");
            
        } else {
            likedSongs.deleteSong();
        }
        
    }                                         

    private void print_likedBTNActionPerformed(java.awt.event.ActionEvent evt) {                                               
        
        likedSongs.printPlaylist();
        
    }                                              

    private void sizeBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
        
        likedSongs.countSongs();
        
    }                                       

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {                                          
        
        String title = titleTF.getText();
        String artist = artistTF.getText();
        
        likedSongs.searchSong(title, artist);
                
    }                                         

    private void moveBTNActionPerformed(java.awt.event.ActionEvent evt) {                                        
//        
//        likedSongs
//        genrePlaylist.addSong(Song song);
//        
    }                                       

    private void repeatTOGGLE2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        
        boolean repeat = false;
        
        if (MusicLibraryGUI.repeatTOGGLE2.isSelected() == true) {
            repeat = true;
            likedSongs.setRepeat();
        } else if (MusicLibraryGUI.repeatTOGGLE2.isSelected() == false) {
            repeat = false;
            likedSongs.setNotRepeat();
        }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MusicLibraryGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MusicLibraryGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel artistLBL;
    public static javax.swing.JTextField artistTF;
    private javax.swing.JLabel backgroundLBL;
    private javax.swing.JMenu colorBlindMode;
    private javax.swing.JLabel colorblindLBL;
    private javax.swing.JMenu date;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton exitBTN;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton moveBTN;
    private javax.swing.JButton print_hiphopBTN;
    private javax.swing.JButton print_likedBTN;
    private javax.swing.JButton print_pianoBTN;
    public static javax.swing.JToggleButton repeatTOGGLE2;
    private javax.swing.JButton searchBTN;
    private javax.swing.JButton sizeBTN;
    private javax.swing.JMenu time;
    private javax.swing.JLabel titleLBL;
    public static javax.swing.JTextField titleTF;
    // End of variables declaration                   
}
